const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {spawnSync}=require('node:child_process');
const source=fs.readFileSync('extensions/vscode/extension.cjs','utf8');
const moduleStub={exports:{}};vm.runInNewContext(source,{require:name=>name==='vscode'?{}:require(name),module:moduleStub,exports:moduleStub.exports,Buffer,console,setTimeout,clearTimeout});
const validate=moduleStub.exports.validatePlan;
test('VS Code adapter accepts UTF-16 engine plans after emoji',()=>{const r=spawnSync('engine/target/release/parzr-engine',[],{input:JSON.stringify({text:'😀 teh mesage.'})+'\n',encoding:'utf8'});assert.equal(r.status,0);const plan=JSON.parse(r.stdout);assert.doesNotThrow(()=>validate('😀 teh mesage.',plan));assert.equal(plan.text,'😀 the message.');});
test('VS Code adapter rejects stale and inconsistent plans',()=>{assert.throws(()=>validate('abc',{text:'x',edits:[{start_utf16:0,end_utf16:3,original:'wrong',replacement:'x'}]}));assert.throws(()=>validate('abc',{text:'wrong',edits:[]}));});
test('VS Code adapter rejects overlapping, duplicate, and invalid ranges',()=>{const edit={start_utf16:0,end_utf16:2,original:'ab',replacement:'x'};assert.throws(()=>validate('abc',{text:'xxc',edits:[edit,edit]}));assert.throws(()=>validate('abc',{text:'',edits:[{...edit,start_utf16:-1}]}));});
test('native messaging host supports multiple framed requests and UTF-8',()=>{const reqs=[{text:'i recieved this.'},{text:'😀 teh mesage.',mode:'professional'}];const chunks=reqs.map(r=>{const data=Buffer.from(JSON.stringify(r));const header=Buffer.alloc(4);header.writeUInt32LE(data.length);return Buffer.concat([header,data]);});const result=spawnSync('engine/target/release/parzr-native-host',[],{input:Buffer.concat(chunks)});assert.equal(result.status,0);let offset=0;const responses=[];while(offset<result.stdout.length){const length=result.stdout.readUInt32LE(offset);offset+=4;responses.push(JSON.parse(result.stdout.subarray(offset,offset+length)));offset+=length;}assert.equal(responses.length,2);assert.equal(responses[0].text,'I received this.');assert.ok(['😀 the message.','😀 The message.'].includes(responses[1].text));});
test('native host refuses oversized frames without allocating their payload',()=>{const header=Buffer.alloc(4);header.writeUInt32LE(0xffffffff);const result=spawnSync('engine/target/release/parzr-native-host',[],{input:header});assert.equal(result.status,0);assert.equal(result.stdout.length,0);});
